name: Sync Leetcode

on:
  workflow_dispatch:     
  schedule:
    - cron: '0 8 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.CSRFTOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: 'solutions'
          verbose: true        # <--- Ensures problem details and stats are pulled
          commit-header: 'Sync LeetCode:' # <--- Clean prefix for your commit title
